### ISSUE TITLE
Should it works for official 2.79b?

### ISSUE THREAD

**Issue by mond-cz** [Pullusb/SB_imgs2video#1]
Hi, thank you for Haddon, I just wanted to try it, but can't see a video file? 
Can you confirm addon is still working? Thanks you

Here is what command line says after last (25th) PNG is rendered.
Is it expected behaviour?

...
Saved: '/Users/x/Desktop/PNG03/img_0025.png'
 Time: 00:00.08 (Saving: 00:00.02)

tail found
/Users/x/Desktop/
__________
"/Users/x/Downloads/ffmpeg" -f image2 -start_number 1 -i "/Users/x/Desktop/PNG03/img_%04d.png" -r 24 -crf 16 -preset veryslow -pix_fmt yuv420p -y "/Users/x/Desktop/img_F.mp4"
__________
Info: generating video...

ffmpeg version 4.0.2-tessus Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.1.0 (clang-902.0.39.2)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

(p.s.: I'm not command line user, just from time to time, but last line of text "Use -h..." was yellow on black background that I haven't seen on mac before. Probably nothing to care about.)

**Comment by Pullusb** [comment]
Hi, yes it's supposed to work in all version since 2.74 (or even less) to current 2.79b version.
It's a bit weird because the command is well constructed and sent but it is as if the system catch only "/Users/x/Downloads/ffmpeg" instead of the full command...
(The message you get is when ffmpeg is called alone, without further argument.)
I don't have any Mac around to run a test but it should have work.

Can you try this version [SB_imgs2video_no-subprocess.zip](https://github.com/Pullusb/SB_imgs2video/files/2238205/SB_imgs2video_no-subprocess.zip) and tell me if it solved your problem ?
The only difference is the command being called differently to the system by python (downside of this method : It will lock your blender interface during the encoding).

**Comment by mond-cz** [comment]
Yes, this version works for me (my iMac) :) I tried it to test at work on my iMac. Both version (official failed in the same way.) I had a time to test just a quick demo, video was done in a second so can't say if interface is freezes for that moment. Sometimes there is a problem with used slash direction in command, but it doesn't seem to be the problem? Anyway thank you even for this version :) Seems to me like a great time saver.
p.s.: Autolunch option works, Open at finish doesn't ... I'm not so tech, but what your script call exactly to let file open? Would it work on mac as well? I love this function with Apples Motion5 app.

Here is what command line sayid:
[info.rtf.zip](https://github.com/Pullusb/SB_imgs2video/files/2242438/info.rtf.zip)
